services:
  mysql:
    image: mysql:8.0
    container_name: fewster-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fewsterdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fewster-network

  app:
    build: .
    container_name: fewster-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fewsterdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - fewster-network

volumes:
  mysql_data:

networks:
  fewster-network:
    driver: bridge